export const SEARCH_VIDEOS = 'SEARCH_VIDEOS';
export const SEARCH_VIDEOS_SUCCESS = 'SEARCH_VIDEOS_SUCCESS';
export const SEARCH_VIDEOS_FAILURE = 'SEARCH_VIDEOS_FAILURE';

export const SELECT_VIDEO = 'SELECT_VIDEO';
